name: sunstone
description: A way to navigate Fluter Vikings.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  auto_size_text: ^3.0.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  intl: ^0.17.0
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15
  timezone: ^0.8.0
  url_launcher: ^6.1.5

dev_dependencies:
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Norse
      fonts:
        - asset: assets/fonts/Norse.otf
        - asset: assets/fonts/Norse-Bold.otf
          weight: 700
